#!/opt/app-root/bin/python

import socket
import time
import os

port = int(5432)

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
while True:
    try:
        s.connect((os.environ["JUPYTERHUB_DATABASE_HOST"], port))
        s.close()
        break
    except socket.error as ex:
        time.sleep(3)
